config/routes.rb
Rails.application.routes.draw do
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text,
            presence: true,
            length: {
              maximum: 140,
              too_long: '%<count>s characters is the maximum allowed'
            }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
    @tweets = Tweet.all.reverse
  end

  def create
    @tweet = Tweet.new(params.require(:tweet).permit(:text))
    respond_to do |format|
      if @tweet.valid?
        @tweet.save
        format.html { redirect_to new_tweet_path, notice: 'Tweet was successfully created.' }
        format.json { render :new, status: :created, location: @tweet }
      else
        format.html { redirect_to new_tweet_path, notice: @tweet.errors[:text][0] }
        format.json { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    respond_to do |format|
      if @tweet.present?
        @tweet.destroy
        format.html { redirect_to new_tweet_path, notice: 'Tweet was successfully deleted.' }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter04</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/new.html.erb
<h1>Alitwitter</h1>

<%= form_with scope: :tweet, url: tweets_path, local: true do |form| %>
  <p>
    <%= form.label :tweet %><br>
    <%= form.text_field :text, required: true, size: 200, id: 'tweet_tweet'%> 
  </p>
 
  <p>
    <%= form.submit 'Post Tweet' %>
  </p>
<% end %>

<%= notice %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><p><%= tweet.created_at %></p></td>
        <td><p><%= tweet.text %></p></td>
        <td><%= link_to 'delete', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>